# k8s/backend/location-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service
spec:
  selector:
    matchLabels:
      app: location-service
  template:
    metadata:
      labels:
        app: location-service
    spec:
      containers:
      - name: location-service
        image: cinema/location-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST
          value: location-db
        - name: DB_USER
          value: location_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: location-db-password
        - name: DB_NAME
          value: location_db
        - name: DB_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: location-service
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: location-service