# k8s/backend/movie-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
spec:
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: cinema/movie-service:latest  # Thay bằng image của bạn
        imagePullPolicy: Never  # Sử dụng image local
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: movie-db
        - name: DB_USER
          value: movie_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: movie-db-password
        - name: DB_NAME
          value: movie_db
        - name: DB_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: movie-service