# k8s/backend/schedule-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-service
spec:
  selector:
    matchLabels:
      app: schedule-service
  template:
    metadata:
      labels:
        app: schedule-service
    spec:
      containers:
      - name: schedule-service
        image: cinema/schedule-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3002
        env:
        - name: MOVIE_SERVICE_URL
          value: "http://movie-service:3000"  # Dùng dấu gạch ngang
        - name: LOCATION_SERVICE_URL
          value: "http://location-service:3001"  # Dùng dấu gạch ngang
        - name: DB_HOST
          value: schedule-db
        - name: DB_USER
          value: schedule_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: schedule-db-password
        - name: DB_NAME
          value: schedule_db
        - name: DB_PORT
          value: "5432"
        - name: MOVIE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: service-config
              key: MOVIE_SERVICE_URL
        - name: LOCATION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: service-config
              key: LOCATION_SERVICE_URL
        - name: RABBITMQ_URL
          value: "amqp://cinema_app:cinema_password@rabbitmq:5672"
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: rabbitmq-user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: rabbitmq-password
---
apiVersion: v1
kind: Service
metadata:
  name: schedule-service
spec:
  ports:
  - port: 3002
    targetPort: 3002
  selector:
    app: schedule-service