# k8s/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  movie-db-password: secret
  location-db-password: secret
  schedule-db-password: secret
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
stringData:
  rabbitmq-user: cinema_app
  rabbitmq-password: cinema_password
---
apiVersion: v1
kind: Secret
metadata:
  name: email-credentials
type: Opaque
stringData:
  email-user: tieuhoangdat2k3@gmail.com
  email-password: fjbt hryy ywpt rxxb